config/routes.rb
Rails.application.routes.draw do

  root 'main#index'
  get 'main/index'
  get '/comment/like' => 'main#like'
  get '/comment/unlike' => 'main#unlike'
  post '/comment/best' => 'main#sort_by'
  post '/comment/latest' => 'main#sort_by'
  post '/' => 'main#create'
  delete '/:id' => 'main#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  has_many :likes

  validates :user_id, presence: true
  validates :content, presence: true, length: { minimum: 5, maximum: 300 }
end

app/models/image.rb
class Image < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :comment

  validates_uniqueness_of :user_id, scope: :comment_id
end
8

app/models/user.rb
class User < ApplicationRecord
  has_many :likes
  has_many :comments, through: :likes, source: :comment

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @comments = Comment.all.sort_by(&:created_at).reverse!
    # @comments = Comment.order(:created_at).page(params[:page])
  end

  def create
    if current_user
      @user = User.find(session[:user_id])
      @comment = Comment.new(comment_params)
      @comment.user_id = session[:user_id]
      @comment.writer = @user.name
      @comment.agree = 0
      @comment.disagree = 0
      @comment.image_id = params[:image_id]

      if @comment.save
        respond_to do |format|
          format.html { redirect_to @comment }
          format.js
        end
      else
        render js: "alert('5자 이상 적어야 이용가능합니다');"
      end
    else
      render js: "alert('로그인 후 이용해주세요.');"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      respond_to do |format|
        format.js
      end
    end
  end

  def like
    if current_user
      @comment = Comment.find(params[:id])
      @like = Like.new(params.permit(:user_id, :comment_id))
      @like.user_id = session[:user_id]
      @like.comment_id = @comment.id

      if @like.save
        params[:vote] == "like" ? @comment.agree += 1 : @comment.disagree += 1
        if @comment.save
          respond_to do |format|
            format.html { redirect_to :back }
            format.js
          end
        end
      else
        render js: "alert('이미 투표에 참여하셨습니다.');"
      end
    else
      render js: "alert('로그인 후 이용해주세요.');"
    end
  end

  def sort_by
    if params[:sort] == "latest"
      @comments = Comment.all.sort_by(&:created_at).reverse!
    else
      @comments = Comment.all.sort_by(&:agree).reverse!
    end
    respond_to do |format|
      format.html { redirect_to @comments }
      format.js
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content, :writer, :agree, :disagree, :user_id, :image_id)
    end
end

app/controllers/session_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to :controller => "main", :action => "index"
  end

  def destroy
    session[:user_id] = nil
    redirect_to :controller => "main", :action => "index"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>President</title>
    <%= csrf_meta_tags %>

    <!-- Resources -->
    <script src="https://www.amcharts.com/lib/3/amcharts.js"></script>
    <script src="https://www.amcharts.com/lib/3/serial.js"></script>
    <script src="https://www.amcharts.com/lib/3/plugins/export/export.min.js"></script>
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
    <script src="https://www.amcharts.com/lib/3/themes/none.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '403383773360454',
          xfbml      : true,
          version    : 'v2.8'
        });
        // FB.AppEvents.logPageView();
      };

      (function(d, s, id){
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) {return;}
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js";
        fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));

    </script>

    <h1 class="title"><a href="/">대선주자에게 묻는다</a></h1>
    <nav class="menu">
      <ul>
        <li><a class="menu-link" href="/">후보에게 질문하기</a></li>
        <li><a class="menu-link" href="/profiles">대선 후보</a></li>
        <li><a class="menu-link" href="#">후보 검증</a></li>
        <li><a class="menu-link" href="#">정책 비교</a></li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/main/_comment.html.erb
<div class="comment" id="comment-<%= comment.id %>">
  <ul>
    <img src="assets/ljm.jpeg">
    <li><span class="writer"><%= comment.writer %></span></li>
    <li><span class="selected-name"><i class="fa fa-check"></i> 이재명 후보님</span></li>
    <li class="content"><p><%= comment.content %></p></li>
    <li class="comment-date-delete">
      <span class="date"><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></span>
      <% if current_user %>
        <% if session[:user_id] = comment.user_id %>
          <span> | </span>
          <%= link_to "삭제", { action: :destroy, id: comment.id }, method: :delete, remote: true, data: { confirm: "댓글을 삭제하시겠습니까?" } %>
        <% end %>
      <% end %>
      <%= link_to comment_like_path(id: comment.id, vote: "unlike"), class: "thumbs", remote: true do %>
        <i class="fa fa-thumbs-o-down" id="thumb-down-<%= comment.id %>"> <%= comment.disagree %></i>
      <% end %>
      <%= link_to comment_like_path(id: comment.id, vote: "like"), class: "thumbs", remote: true do %>
        <i class="fa fa-thumbs-o-up" id="thumb-up-<%= comment.id %>"> <%= comment.agree %></i>
      <% end %>
  </li>
</ul>
</div>

app/views/main/_sort_by.erb
<% comments.each do |comment| %>
  <%= render partial: "comment", locals: { comment: comment } %>
<% end %>

app/views/main/create.js.erb
(function($){
  $("#comment-content").val("");
  var html = "<%= escape_javascript(render(partial: 'comment', locals: {comment: @comment})) %>";
  $("#comments").append(html);
})(jQuery)


// $(function() {
//   //
// });

app/views/main/destroy.js.erb
(function($){
  $("#comment-<%= @comment.id %>").remove();
})(jQuery)

app/views/main/index.html.erb
<!-- 디데이 -->
<div class="d-day area">
  <h2>D-51</h2>
</div>

<!-- 대선후보 지지율 -->
<div class="rating-chart area">
  <h2><%= Date.today %> 대선 후보 지지도 (%)</h2>
  <article>
    <span class="left-button btn">&#8249;</span>
    <div id="chartdiv"></div>
    <span class="right-button btn">&#8250;</span>
  </article>
</div>


<div class="comments area">
  <h2>후보에게 질문하기</h2>

  <div class="input-area">

    <!-- 페이스북 로그인 -->
    <div class="login-btn" id="user-widget">
      <% if current_user %>
        <strong><%= current_user.name %>님</strong>!
        <%= link_to "Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "페이스북으로 로그인하기", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>

    <!-- 댓글 입력창-->
    <%= form_for :comment, remote: true do |f| %>
      <div class="candidate-select">
        <%= f.select :image_id,
          options_for_select([['질문해주실 후보를 선택해주세요.', 0],['문재인', 1], ['이재명', 3], ['안희정', 2], ['안철수', 4], ['심상정', 5]], params[:image_id]), {}, { :class => "select-box form-control" } %>
        <ul>
          <li><div class="thumbnail first" id="image-1">
            <img class="image-picker first" src="assets/moon.jpeg" alt="1">
          </div></li>
          <li><div class="thumbnail" id="image-3">
            <img class="image-picker" src="assets/ljm.jpeg" alt="3">
          </div></li>
          <li><div class="thumbnail" id="image-2">
            <img class="image-picker" src="assets/ahj.jpeg" alt="2">
          </div></li>
          <li><div class="thumbnail" id="image-4">
            <img class="image-picker" src="assets/acs.jpeg" alt="4">
          </div></li>
          <li><div class="thumbnail last" id="image-5">
            <img class="image-picker last" src="assets/ssj.jpeg" alt="5">
          </div></li>
        </ul>
      </div>

      <%= f.text_area :content, :class => "form-control", :id => "comment-content", :rows => "2", :maxlength => "300", :placeholder => "질문을 입력하세요" %>
      <% if current_user %>
        <%= f.submit "등록", :class => "btn btn-info" %>
      <% else %>
        <button class="btn btn-info">등록</button>
      <% end %>
      <span id="counter"> 0/300</span>
    <% end %>
  </div>

  <!-- 댓글 목록 -->
  <div class="comment-list" id="comments">
    <div class="sort-group">
      <%= link_to "호감순", comment_best_path(sort: "best"), :class => "best sort", :method => :post, remote: true %>
      <%= link_to "최신순", comment_latest_path(sort: "latest"), :class => "latest sort on", :method => :post, remote: true %>
    </div>
    <div id="comments-js" >
      <%= render partial: "sort_by", locals: { comments: @comments } %>
    </div>
  </div>
</div>

app/views/main/index.js.erb
// $("#comments").append("<%= escape_javascript(render(@comments)) %>");

app/views/main/like.js.erb
(function($){
  $("#thumb-up-<%= @comment.id %>").html("<%= @comment.agree %>");
  $("#thumb-down-<%= @comment.id %>").html("<%= @comment.disagree %>");
})(jQuery)

app/views/main/sort_by.js.erb
(function($){
  var html = "<%= escape_javascript(render(partial: 'sort_by', locals: {comments: @comments})) %>";
  $("#comments-js").empty();
  $("#comments-js").append(html);
})(jQuery)